algoritmo "calculadora"
// Função : apresente um numero e apresente o dobro do numero anterior
// Autor : Caic Henriques Rodridues
// Data : 20/10/2020
// Seção de Declarações 
var
nun, resul, cont: inteiro

inicio
//entrada
escreval("Digite um valor para montar a tabuada")
leia(nun)
para cont de 1 ate 100 faca
   resul <- nun*cont
   escreval(nun," x ",cont," = ", resul)
fimpara
fimalgoritmo
